import type { FacilityInfo } from "@/types";

export function getMockFacilities(): FacilityInfo[] {
  return [
    {
      id: "f-001",
      name: "산음자연휴양림",
      type: "recreation_forest",
      address: "경기도 양평군 단월면 고북길 347",
      lat: 37.62,
      lng: 127.54,
      tel: "031-774-8133",
      intro: "치유의 숲이 조성된 잣나무와 낙엽송 원시림",
      operatingHours: "09:00 - 18:00 (화요일 휴무)",
      programs: ["산림치유프로그램", "숲해설프로그램", "목공예체험"],
      trails: [
        { name: "치유의 숲길", distanceKm: 1.5, difficulty: "easy", estimatedMinutes: 40 },
        { name: "건강증진코스", distanceKm: 3.2, difficulty: "moderate", estimatedMinutes: 90 },
      ],
      accessibility: {
        wheelchair: true,
        stroller: true,
        parking: true,
        restroom: true,
        elevator: false,
        helpdog: true,
      },
      imageUrl: "",
    },
    {
      id: "f-002",
      name: "축령산자연휴양림",
      type: "recreation_forest",
      address: "경기도 남양주시 수동면 축령산로 299",
      lat: 37.63,
      lng: 127.15,
      programs: ["숲속명상", "잣나무숲 트레킹"],
      trails: [{ name: "둘레길", distanceKm: 2.0, difficulty: "easy", estimatedMinutes: 60 }],
      accessibility: {
        wheelchair: false,
        stroller: false,
        parking: true,
        restroom: true,
        elevator: false,
        helpdog: true,
      },
      imageUrl: "",
    },
    {
      id: "f-003",
      name: "국립횡성숲체원",
      type: "education",
      address: "강원도 횡성군 둔내면 청태산로 777",
      lat: 37.49,
      lng: 128.15,
      intro: "국내 최초의 산림교육 전문 시설",
      programs: ["오감체험", "숲속 다도", "가족캠프"],
      trails: [
        {
          name: "늘솔길 (무장애 데크로)",
          distanceKm: 1.2,
          difficulty: "easy",
          estimatedMinutes: 30,
        },
      ],
      accessibility: {
        wheelchair: true,
        stroller: true,
        parking: true,
        restroom: true,
        elevator: true,
        helpdog: true,
      },
      imageUrl: "",
    },
    {
      id: "f-004",
      name: "장성편백치유의숲",
      type: "healing_forest",
      address: "전라남도 장성군 서삼면 모암리 산98",
      lat: 35.3,
      lng: 126.79,
      intro: "전국 최대 규모의 편백나무 숲",
      programs: ["편백숲 맨발걷기", "피톤치드 명상"],
      trails: [
        { name: "치유의 길", distanceKm: 2.5, difficulty: "moderate", estimatedMinutes: 80 },
      ],
      accessibility: {
        wheelchair: false,
        stroller: true,
        parking: true,
        restroom: true,
        elevator: false,
        helpdog: false,
      },
      imageUrl: "",
    },
    {
      id: "f-005",
      name: "국립대관령치유의숲",
      type: "healing_forest",
      address: "강원특별자치도 강릉시 성산면 어흘리 333-1",
      lat: 37.71,
      lng: 128.81,
      intro: "금강소나무 숲에서의 프리미엄 산림치유",
      programs: ["수(水)테라피", "향기명상", "싱잉볼 명상"],
      trails: [
        { name: "금강송 숲길", distanceKm: 1.8, difficulty: "easy", estimatedMinutes: 50 },
        { name: "도전의 숲길", distanceKm: 4.0, difficulty: "hard", estimatedMinutes: 120 },
      ],
      accessibility: {
        wheelchair: true,
        stroller: true,
        parking: true,
        restroom: true,
        elevator: false,
        helpdog: false,
      },
      imageUrl: "",
    },
  ];
}
