/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as MapRouteImport } from './routes/map'
import { Route as KidsMapRouteImport } from './routes/kids-map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result/$id'
import { Route as FacilitiesFacilityIdRouteImport } from './routes/facilities/$facilityId'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiUvIndexRouteImport } from './routes/api/uv-index'
import { Route as ApiTraditionalVillageForestsRouteImport } from './routes/api/traditional-village-forests'
import { Route as ApiTourismRouteImport } from './routes/api/tourism'
import { Route as ApiRecreationForestsRouteImport } from './routes/api/recreation-forests'
import { Route as ApiRecommendationRouteImport } from './routes/api/recommendation'
import { Route as ApiNaverDirectionRouteImport } from './routes/api/naver-direction'
import { Route as ApiKidsForestsRouteImport } from './routes/api/kids-forests'
import { Route as ApiHealingForestsRouteImport } from './routes/api/healing-forests'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiForestPlantsRouteImport } from './routes/api/forest-plants'
import { Route as ApiForestPlantImagesRouteImport } from './routes/api/forest-plant-images'
import { Route as ApiForestEducationProgramsRouteImport } from './routes/api/forest-education-programs'
import { Route as ApiFacilityHomepageAnalysisRouteImport } from './routes/api/facility-homepage-analysis'
import { Route as ApiBarrierFreeTourismRouteImport } from './routes/api/barrier-free-tourism'
import { Route as ApiAirQualityRouteImport } from './routes/api/air-quality'

const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsMapRoute = KidsMapRouteImport.update({
  id: '/kids-map',
  path: '/kids-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesFacilityIdRoute = FacilitiesFacilityIdRouteImport.update({
  id: '/facilities/$facilityId',
  path: '/facilities/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUvIndexRoute = ApiUvIndexRouteImport.update({
  id: '/api/uv-index',
  path: '/api/uv-index',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTraditionalVillageForestsRoute =
  ApiTraditionalVillageForestsRouteImport.update({
    id: '/api/traditional-village-forests',
    path: '/api/traditional-village-forests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTourismRoute = ApiTourismRouteImport.update({
  id: '/api/tourism',
  path: '/api/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecreationForestsRoute = ApiRecreationForestsRouteImport.update({
  id: '/api/recreation-forests',
  path: '/api/recreation-forests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationRoute = ApiRecommendationRouteImport.update({
  id: '/api/recommendation',
  path: '/api/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNaverDirectionRoute = ApiNaverDirectionRouteImport.update({
  id: '/api/naver-direction',
  path: '/api/naver-direction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKidsForestsRoute = ApiKidsForestsRouteImport.update({
  id: '/api/kids-forests',
  path: '/api/kids-forests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealingForestsRoute = ApiHealingForestsRouteImport.update({
  id: '/api/healing-forests',
  path: '/api/healing-forests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForestPlantsRoute = ApiForestPlantsRouteImport.update({
  id: '/api/forest-plants',
  path: '/api/forest-plants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForestPlantImagesRoute = ApiForestPlantImagesRouteImport.update({
  id: '/api/forest-plant-images',
  path: '/api/forest-plant-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForestEducationProgramsRoute =
  ApiForestEducationProgramsRouteImport.update({
    id: '/api/forest-education-programs',
    path: '/api/forest-education-programs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFacilityHomepageAnalysisRoute =
  ApiFacilityHomepageAnalysisRouteImport.update({
    id: '/api/facility-homepage-analysis',
    path: '/api/facility-homepage-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBarrierFreeTourismRoute = ApiBarrierFreeTourismRouteImport.update({
  id: '/api/barrier-free-tourism',
  path: '/api/barrier-free-tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAirQualityRoute = ApiAirQualityRouteImport.update({
  id: '/api/air-quality',
  path: '/api/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/curation': typeof CurationRoute
  '/home': typeof HomeRoute
  '/kids-map': typeof KidsMapRoute
  '/map': typeof MapRoute
  '/mypage': typeof MypageRoute
  '/plants': typeof PlantsRoute
  '/programs': typeof ProgramsRoute
  '/recommend': typeof RecommendRoute
  '/records': typeof RecordsRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/barrier-free-tourism': typeof ApiBarrierFreeTourismRoute
  '/api/facility-homepage-analysis': typeof ApiFacilityHomepageAnalysisRoute
  '/api/forest-education-programs': typeof ApiForestEducationProgramsRoute
  '/api/forest-plant-images': typeof ApiForestPlantImagesRoute
  '/api/forest-plants': typeof ApiForestPlantsRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/healing-forests': typeof ApiHealingForestsRoute
  '/api/kids-forests': typeof ApiKidsForestsRoute
  '/api/naver-direction': typeof ApiNaverDirectionRoute
  '/api/recommendation': typeof ApiRecommendationRoute
  '/api/recreation-forests': typeof ApiRecreationForestsRoute
  '/api/tourism': typeof ApiTourismRoute
  '/api/traditional-village-forests': typeof ApiTraditionalVillageForestsRoute
  '/api/uv-index': typeof ApiUvIndexRoute
  '/api/weather': typeof ApiWeatherRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/curation': typeof CurationRoute
  '/home': typeof HomeRoute
  '/kids-map': typeof KidsMapRoute
  '/map': typeof MapRoute
  '/mypage': typeof MypageRoute
  '/plants': typeof PlantsRoute
  '/programs': typeof ProgramsRoute
  '/recommend': typeof RecommendRoute
  '/records': typeof RecordsRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/barrier-free-tourism': typeof ApiBarrierFreeTourismRoute
  '/api/facility-homepage-analysis': typeof ApiFacilityHomepageAnalysisRoute
  '/api/forest-education-programs': typeof ApiForestEducationProgramsRoute
  '/api/forest-plant-images': typeof ApiForestPlantImagesRoute
  '/api/forest-plants': typeof ApiForestPlantsRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/healing-forests': typeof ApiHealingForestsRoute
  '/api/kids-forests': typeof ApiKidsForestsRoute
  '/api/naver-direction': typeof ApiNaverDirectionRoute
  '/api/recommendation': typeof ApiRecommendationRoute
  '/api/recreation-forests': typeof ApiRecreationForestsRoute
  '/api/tourism': typeof ApiTourismRoute
  '/api/traditional-village-forests': typeof ApiTraditionalVillageForestsRoute
  '/api/uv-index': typeof ApiUvIndexRoute
  '/api/weather': typeof ApiWeatherRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/curation': typeof CurationRoute
  '/home': typeof HomeRoute
  '/kids-map': typeof KidsMapRoute
  '/map': typeof MapRoute
  '/mypage': typeof MypageRoute
  '/plants': typeof PlantsRoute
  '/programs': typeof ProgramsRoute
  '/recommend': typeof RecommendRoute
  '/records': typeof RecordsRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/barrier-free-tourism': typeof ApiBarrierFreeTourismRoute
  '/api/facility-homepage-analysis': typeof ApiFacilityHomepageAnalysisRoute
  '/api/forest-education-programs': typeof ApiForestEducationProgramsRoute
  '/api/forest-plant-images': typeof ApiForestPlantImagesRoute
  '/api/forest-plants': typeof ApiForestPlantsRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/healing-forests': typeof ApiHealingForestsRoute
  '/api/kids-forests': typeof ApiKidsForestsRoute
  '/api/naver-direction': typeof ApiNaverDirectionRoute
  '/api/recommendation': typeof ApiRecommendationRoute
  '/api/recreation-forests': typeof ApiRecreationForestsRoute
  '/api/tourism': typeof ApiTourismRoute
  '/api/traditional-village-forests': typeof ApiTraditionalVillageForestsRoute
  '/api/uv-index': typeof ApiUvIndexRoute
  '/api/weather': typeof ApiWeatherRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/curation'
    | '/home'
    | '/kids-map'
    | '/map'
    | '/mypage'
    | '/plants'
    | '/programs'
    | '/recommend'
    | '/records'
    | '/api/air-quality'
    | '/api/barrier-free-tourism'
    | '/api/facility-homepage-analysis'
    | '/api/forest-education-programs'
    | '/api/forest-plant-images'
    | '/api/forest-plants'
    | '/api/geocode'
    | '/api/healing-forests'
    | '/api/kids-forests'
    | '/api/naver-direction'
    | '/api/recommendation'
    | '/api/recreation-forests'
    | '/api/tourism'
    | '/api/traditional-village-forests'
    | '/api/uv-index'
    | '/api/weather'
    | '/facilities/$facilityId'
    | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/curation'
    | '/home'
    | '/kids-map'
    | '/map'
    | '/mypage'
    | '/plants'
    | '/programs'
    | '/recommend'
    | '/records'
    | '/api/air-quality'
    | '/api/barrier-free-tourism'
    | '/api/facility-homepage-analysis'
    | '/api/forest-education-programs'
    | '/api/forest-plant-images'
    | '/api/forest-plants'
    | '/api/geocode'
    | '/api/healing-forests'
    | '/api/kids-forests'
    | '/api/naver-direction'
    | '/api/recommendation'
    | '/api/recreation-forests'
    | '/api/tourism'
    | '/api/traditional-village-forests'
    | '/api/uv-index'
    | '/api/weather'
    | '/facilities/$facilityId'
    | '/result/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/community'
    | '/curation'
    | '/home'
    | '/kids-map'
    | '/map'
    | '/mypage'
    | '/plants'
    | '/programs'
    | '/recommend'
    | '/records'
    | '/api/air-quality'
    | '/api/barrier-free-tourism'
    | '/api/facility-homepage-analysis'
    | '/api/forest-education-programs'
    | '/api/forest-plant-images'
    | '/api/forest-plants'
    | '/api/geocode'
    | '/api/healing-forests'
    | '/api/kids-forests'
    | '/api/naver-direction'
    | '/api/recommendation'
    | '/api/recreation-forests'
    | '/api/tourism'
    | '/api/traditional-village-forests'
    | '/api/uv-index'
    | '/api/weather'
    | '/facilities/$facilityId'
    | '/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  CurationRoute: typeof CurationRoute
  HomeRoute: typeof HomeRoute
  KidsMapRoute: typeof KidsMapRoute
  MapRoute: typeof MapRoute
  MypageRoute: typeof MypageRoute
  PlantsRoute: typeof PlantsRoute
  ProgramsRoute: typeof ProgramsRoute
  RecommendRoute: typeof RecommendRoute
  RecordsRoute: typeof RecordsRoute
  ApiAirQualityRoute: typeof ApiAirQualityRoute
  ApiBarrierFreeTourismRoute: typeof ApiBarrierFreeTourismRoute
  ApiFacilityHomepageAnalysisRoute: typeof ApiFacilityHomepageAnalysisRoute
  ApiForestEducationProgramsRoute: typeof ApiForestEducationProgramsRoute
  ApiForestPlantImagesRoute: typeof ApiForestPlantImagesRoute
  ApiForestPlantsRoute: typeof ApiForestPlantsRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiHealingForestsRoute: typeof ApiHealingForestsRoute
  ApiKidsForestsRoute: typeof ApiKidsForestsRoute
  ApiNaverDirectionRoute: typeof ApiNaverDirectionRoute
  ApiRecommendationRoute: typeof ApiRecommendationRoute
  ApiRecreationForestsRoute: typeof ApiRecreationForestsRoute
  ApiTourismRoute: typeof ApiTourismRoute
  ApiTraditionalVillageForestsRoute: typeof ApiTraditionalVillageForestsRoute
  ApiUvIndexRoute: typeof ApiUvIndexRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  FacilitiesFacilityIdRoute: typeof FacilitiesFacilityIdRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-map': {
      id: '/kids-map'
      path: '/kids-map'
      fullPath: '/kids-map'
      preLoaderRoute: typeof KidsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/$facilityId': {
      id: '/facilities/$facilityId'
      path: '/facilities/$facilityId'
      fullPath: '/facilities/$facilityId'
      preLoaderRoute: typeof FacilitiesFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uv-index': {
      id: '/api/uv-index'
      path: '/api/uv-index'
      fullPath: '/api/uv-index'
      preLoaderRoute: typeof ApiUvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traditional-village-forests': {
      id: '/api/traditional-village-forests'
      path: '/api/traditional-village-forests'
      fullPath: '/api/traditional-village-forests'
      preLoaderRoute: typeof ApiTraditionalVillageForestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tourism': {
      id: '/api/tourism'
      path: '/api/tourism'
      fullPath: '/api/tourism'
      preLoaderRoute: typeof ApiTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recreation-forests': {
      id: '/api/recreation-forests'
      path: '/api/recreation-forests'
      fullPath: '/api/recreation-forests'
      preLoaderRoute: typeof ApiRecreationForestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendation': {
      id: '/api/recommendation'
      path: '/api/recommendation'
      fullPath: '/api/recommendation'
      preLoaderRoute: typeof ApiRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/naver-direction': {
      id: '/api/naver-direction'
      path: '/api/naver-direction'
      fullPath: '/api/naver-direction'
      preLoaderRoute: typeof ApiNaverDirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kids-forests': {
      id: '/api/kids-forests'
      path: '/api/kids-forests'
      fullPath: '/api/kids-forests'
      preLoaderRoute: typeof ApiKidsForestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healing-forests': {
      id: '/api/healing-forests'
      path: '/api/healing-forests'
      fullPath: '/api/healing-forests'
      preLoaderRoute: typeof ApiHealingForestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forest-plants': {
      id: '/api/forest-plants'
      path: '/api/forest-plants'
      fullPath: '/api/forest-plants'
      preLoaderRoute: typeof ApiForestPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forest-plant-images': {
      id: '/api/forest-plant-images'
      path: '/api/forest-plant-images'
      fullPath: '/api/forest-plant-images'
      preLoaderRoute: typeof ApiForestPlantImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forest-education-programs': {
      id: '/api/forest-education-programs'
      path: '/api/forest-education-programs'
      fullPath: '/api/forest-education-programs'
      preLoaderRoute: typeof ApiForestEducationProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facility-homepage-analysis': {
      id: '/api/facility-homepage-analysis'
      path: '/api/facility-homepage-analysis'
      fullPath: '/api/facility-homepage-analysis'
      preLoaderRoute: typeof ApiFacilityHomepageAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/barrier-free-tourism': {
      id: '/api/barrier-free-tourism'
      path: '/api/barrier-free-tourism'
      fullPath: '/api/barrier-free-tourism'
      preLoaderRoute: typeof ApiBarrierFreeTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/air-quality': {
      id: '/api/air-quality'
      path: '/api/air-quality'
      fullPath: '/api/air-quality'
      preLoaderRoute: typeof ApiAirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  CurationRoute: CurationRoute,
  HomeRoute: HomeRoute,
  KidsMapRoute: KidsMapRoute,
  MapRoute: MapRoute,
  MypageRoute: MypageRoute,
  PlantsRoute: PlantsRoute,
  ProgramsRoute: ProgramsRoute,
  RecommendRoute: RecommendRoute,
  RecordsRoute: RecordsRoute,
  ApiAirQualityRoute: ApiAirQualityRoute,
  ApiBarrierFreeTourismRoute: ApiBarrierFreeTourismRoute,
  ApiFacilityHomepageAnalysisRoute: ApiFacilityHomepageAnalysisRoute,
  ApiForestEducationProgramsRoute: ApiForestEducationProgramsRoute,
  ApiForestPlantImagesRoute: ApiForestPlantImagesRoute,
  ApiForestPlantsRoute: ApiForestPlantsRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiHealingForestsRoute: ApiHealingForestsRoute,
  ApiKidsForestsRoute: ApiKidsForestsRoute,
  ApiNaverDirectionRoute: ApiNaverDirectionRoute,
  ApiRecommendationRoute: ApiRecommendationRoute,
  ApiRecreationForestsRoute: ApiRecreationForestsRoute,
  ApiTourismRoute: ApiTourismRoute,
  ApiTraditionalVillageForestsRoute: ApiTraditionalVillageForestsRoute,
  ApiUvIndexRoute: ApiUvIndexRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  FacilitiesFacilityIdRoute: FacilitiesFacilityIdRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
